/*Purpose: Apex Class for TEST_AfterUpdate Page.
========================================================================
 History                                                           
    -------                                                          
 VERSION     AUTHOR                 DATE                    DETAIL                                 
     1.0 -   Abhay                 12/28/2011       Apex Class for TEST_AfterUpdate Page.
======================================================================== 
*/
@isTest
private class TEST_AfterUpdateTriggers {

/*
    static testMethod void myUnitTest() {
        GC_UtilityClassTestData td=new GC_UtilityClassTestData();
        Codes__c codes=td.createCodesTestData(); 
        RecordType rt1=[Select Id,Name from RecordType where sobjecttype='Codes__c' and recordtype.Name='Drug Disease'];
     system.debug('---------------rt  before---------aby---'+codes.RecordTypeId);
        codes.RecordTypeId= rt1.id;
        codes.Professional__c='no';        
        codes.Result_of_Service_Codes__c='no';
        update codes;
         system.debug('---------------rt  after---------aby---'+codes.RecordTypeId);
       // update codes;
    }
    */
}