@isTest
private class Test_Clinical_Program_Opportunities {
    /*static testMethod void validateCaseInsert() {
        
        Account testAcct = new Account();
        testAcct.Name='Test Account';
        insert testAcct;
        
        AccountTeamMember testMbr = new AccountTeamMember();
        testMbr.TeamMemberRole='Pharmacy Account Manager';
        testMbr.AccountId=testAcct.Id;
        User u = [Select Id,Name from User where Name='Becca Allen'];
        testMbr.UserId=u.id;
        insert testMbr;
        
        Opportunity testOp = new Opportunity();
        testOp.AccountId=testAcct.Id;
        RecordType rt= [Select Id,Name from RecordType where DeveloperName='RX_Clinical_Programs'];
        testOp.RecordTypeId=rt.id;
        testOp.Name='Test Opportunity';
        testOp.StageName='Negotiation';
        testOp.CloseDate=system.today();
        insert testOp;
        testOp.StageName='Closed Won';
        update testOp;
    }*/

}